# 监控间隔配置
intervals:
  check: 60  # 检查间隔(秒)
  cleanup: 86400  # 清理间隔(秒)
  aggregation: 300  # 数据聚合间隔(秒)

# 资源阈值配置
thresholds:
  cpu: 90  # CPU使用率阈值(%)
  memory: 90  # 内存使用率阈值(%)
  disk: 90  # 磁盘使用率阈值(%)

# 重试配置
retry:
  max_attempts: 3  # 最大重试次数
  delay: 60  # 重试间隔(秒)
  backoff_factor: 2  # 重试延迟增长因子

# 数据保留配置
data_retention:
  days: 30  # 数据保留天数

# 服务配置
services:
  redis:
    port: 6379
    startup_timeout: 30
    health_check:
      interval: 10
      timeout: 5
      retries: 3
    dependencies: []
    
  celery:
    process: "celery"
    startup_timeout: 60
    health_check:
      interval: 30
      timeout: 10
      retries: 3
    dependencies: ["redis"]
    
  flask:
    port: 5000
    url: "http://localhost:5000/"
    startup_timeout: 30
    health_check:
      interval: 15
      timeout: 5
      retries: 3
    dependencies: ["redis", "celery"]

# 告警配置
alerts:
  email:
    enabled: true
    smtp_server: "${SMTP_SERVER}"
    smtp_port: "${SMTP_PORT}"
    username: "${SMTP_USER}"
    password: "${SMTP_PASS}"
    from_address: "${SMTP_FROM}"
    to_addresses: "${SMTP_TO}"
    use_tls: true
    cert_verify: true
    
  webhook:
    enabled: false
    url: "https://hooks.slack.com/services/xxx"
    
  throttling:
    default_interval: 1800  # 默认告警间隔(秒)
    critical_interval: 300  # 严重告警间隔(秒)

# 数据聚合配置
aggregation:
  intervals:
    - 300  # 5分钟
    - 3600  # 1小时
    - 86400  # 1天
  metrics:
    - name: "cpu_usage"
      type: "avg"
    - name: "memory_usage"
      type: "avg"
    - name: "disk_usage"
      type: "max" 

# 进程优先级配置
process_priority:
  redis: "high"
  celery: "normal"
  flask: "normal"
  background_tasks: "low"

# 进程资源限制
process_limits:
  redis:
    memory_max: 1024  # MB
    cpu_affinity: [0, 1]  # CPU核心
  celery:
    memory_max: 2048
    cpu_affinity: [0, 1, 2, 3]
  flask:
    memory_max: 512
    cpu_affinity: [0, 1] 

# 进程重启策略
restart_policy:
  max_restarts: 3  # 最大重启次数
  min_interval: 60  # 最小重启间隔(秒)
  backoff_factor: 2  # 重试延迟增长因子
  max_backoff: 300  # 最大重试延迟(秒)

# 进程健康检查配置
health_check:
  interval: 30  # 检查间隔(秒)
  timeout: 5   # 检查超时(秒)
  thresholds:
    cpu_max: 90  # CPU使用率阈值(%)
    memory_max: 90  # 内存使用率阈值(%)
    response_timeout: 5  # 响应超时(秒)
  
  # 服务特定配置
  services:
    flask:
      url: "http://localhost:5000/health"
      expected_status: 200
      response_pattern: '{"status":"ok"}'
    
    celery:
      check_command: "celery -A app.celery status"
      expected_output: "OK"
    
    redis:
      check_command: "redis-cli ping"
      expected_output: "PONG"